//jshint ignore: start
const products = Object.freeze([
	{
		id: "adb6f52b-c959-4408-b3ce-d9f425c448dc",
		category: "Kulaklıklar",
		subcategory: "Kulak Üstü",
		brand: "Sennheiser",
		name: "HD 600 Open Back",
		exp: "Profesyonel Kulalık",
		details: "Bu profesyonel kulaklık sayesinde oyunlarınızın içinde gibi hissedeceksiniz. Gürültü önleyici mikrofonu sayesinde etraftan gelen sesleri paylaşmak zorunda kalmayacaksınız.",
		color: ["black", "red"],
		detailedlist: ["2m kablo uzunluğu", "Genişlik ayarı", "360 derece dönebilen earpad"],
		price: 1295,
		discount: 30,
		attributes: ["Mic", "RGB"],
		images: ["GH-903.png", "octave-en-v1.png"],
		featured: true,
		slider: true,
    featuredbg: "blue"
	},
  {
		id: "0768b4d2-bde7-42d3-9573-cbd96679f1a0",
		category: "Kulaklıklar",
		subcategory: "Kulak Üstü",
		brand: "Sony",
		name: "WH-1000XM4",
		exp: "Gürültü Engelleme Özellikli Kablosuz Kulaklık",
		details: "Bu profesyonel kulaklık sayesinde oyunlarınızın içinde gibi hissedeceksiniz. Gürültü önleyici mikrofonu sayesinde etraftan gelen sesleri paylaşmak zorunda kalmayacaksınız.",
		color: ["silver"],
		detailedlist: ["Kablosuz", "Genişlik ayarı"],
		price: 4999,
		discount: 0,
		attributes: ["Bluetooth", "Mic", "RGB"],
		images: ["WH-1000XM4.png"],
		featured: true,
		slider: false,
    featuredbg: "green"
	},
	{
		id: "11eced26-c7d2-4053-a49e-45474b9c0e9d",
		category: "Kulaklıklar",
		subcategory: "Kulak Üstü",
		brand: "Rockerz",
		name: "Rockerz 550",
		exp: "Gürültü Engelleme Özellikli Kablosuz Kulaklık",
		details: "Bu kulaklık sayesinde oyunlarınızın içinde gibi hissedeceksiniz. Gürültü önleyici mikrofonu sayesinde etraftan gelen sesleri paylaşmak zorunda kalmayacaksınız.",
		color: ["green", "blue", "red"],
		detailedlist: ["Kablosuz", "Genişlik ayarı", "Ergonomik Tasarım"],
		price: 4999,
		discount: 0,
		attributes: ["Bluetooth", "Mic", "RGB"],
		images: ["Rockerz-500.png"],
		featured: true,
		slider: false,
    featuredbg: "red"
	},
	{
		id: "2687ccdf-58a6-4db1-8f67-ad73baa1cf62",
		category: "Kulaklıklar",
		subcategory: "Kulak Üstü",
		brand: "Octave",
		name: "Rockerz En V1",
		exp: "Gürültü Engelleme Özellikli Kablosuz Kulaklık",
		details: "Bu kulaklık sayesinde oyunlarınızın içinde gibi hissedeceksiniz. Gürültü önleyici mikrofonu sayesinde etraftan gelen sesleri paylaşmak zorunda kalmayacaksınız.",
		color: ["green", "navy", "orange", "lime"],
		detailedlist: ["1.5m kablo", "Genişlik ayarı", "Ergonomik Tasarım"],
		price: 2885,
		discount: 3,
		attributes: ["Mic", "RGB"],
		images: ["octave-en-v1.png"],
		featured: false,
		slider: false,
    featuredbg: "orange"
	},
  {
		id: "2687ccdf-58a6-4db1-8e67-ad73baa1cf62",
		category: "Kulaklıklar",
		subcategory: "Kulak Üstü",
		brand: "Octave",
		name: "Sloppy",
		exp: "Gürültü Engelleme Özellikli Kablosuz Kulaklık",
		details: "Bu kulaklık sayesinde oyunlarınızın içinde gibi hissedeceksiniz. Gürültü önleyici mikrofonu sayesinde etraftan gelen sesleri paylaşmak zorunda kalmayacaksınız.",
		color: ["green", "purple", "yellow"],
		detailedlist: ["1.5m kablo", "Genişlik ayarı", "Ergonomik Tasarım"],
		price: 2885,
		discount: 0,
		attributes: ["Mic", "RGB"],
		images: ["octave-en-v1.png", ],
		featured: false,
		slider: false,
    featuredbg: "hotpink"
	},
  {
		id: "2687ccdf-58a6-8e67-4db1-ad73baa1cf62",
		category: "Kulaklıklar",
		subcategory: "Kulak Üstü",
		brand: "Octave",
		name: "Ponny En V3",
		exp: "Gürültü Engelleme Özellikli Kablosuz Kulaklık",
		details: "Bu kulaklık sayesinde oyunlarınızın içinde gibi hissedeceksiniz. Gürültü önleyici mikrofonu sayesinde etraftan gelen sesleri paylaşmak zorunda kalmayacaksınız.",
		color: ["gold", "pink", "violet"],
		detailedlist: ["1.5m kablo", "Genişlik ayarı", "Ergonomik Tasarım"],
		price: 2885,
		discount: 10,
		attributes: ["Mic", "RGB"],
		images: ["octave-en-v1.png"],
		featured: false,
		slider: true,
    featuredbg: "gray"
	},
  {
		id: "26a7ccdf-56a6-8e67-4db1-ad73baa1cf62",
		category: "Bilgisayar",
		subcategory: "Dizüstü",
		brand: "Huawei",
		name: "Matebook D15",
		exp: "i3-10110U işlemcili dizüstü bilgisayar ",
		details: "Bütün işlerinizi halledebileceğiniz, i3 işlemcili dizüstü bilgisayar",
		color: ["silver"],
		detailedlist: ["10th Gen Intel Core i3-10110U", "8GB Ram", "256GB SSD", " Intel UHD Graphics 620", "Full HD", "15.6&quot;", "Windows 10 Home"],
		price: 7200,
		discount: 1,
		attributes: ["i3-10110U", "8GB Ram", "256GB SSD", "Full HD", "15.6&quot;", "Windows 10 Home"],
		images: ["huavei-D15.png", "h-d15-2.webp", "h-d15-3.webp", "h-d15-4.webp", "h-d15-5.webp"],
		featured: true,
		slider: true,
    featuredbg: "violet"
	},
  {
		id: "c8584e82-ba63-4e20-a8e6-ca238631b9ed",
		category: "Bilgisayar",
		subcategory: "Dizüstü",
		brand: "Apple",
		name: "Macbook Air",
		exp: "APPLE MGNA3TU/A MacBook Air 13.3&quot; Apple M1/512GB SSD/ Laptop Silver",
		details: "Bütün işlerinizi halledebileceğiniz, M1 işlemcili Apple Dizüstü",
		color: ["silver"],
		detailedlist: ["MGNA3TU", "M1", "8 çekirdekli", "13.3&quot;", "512GB SSD", "HD-ready", "15.6&quot;", "2560 x 1600"],
		price: 20699,
		discount: 0,
		attributes: ["M1", "8 çekirdekli", "13.3&quot;", "512GB SSD", "HD-ready", "15.6&quot;", "2560 x 1600"],
		images: ["MGNA3TU-1.png", "MGNA3TU-2.webp"],
		featured: true,
		slider: true,
    featuredbg: "silver"
	},
  {
		id: "28e8a3ea-68c8-407b-a0d6-5b7a89dd0d8a",
		category: "Bilgisayar",
		subcategory: "Dizüstü",
		brand: "HP",
		name: "4P3S3ES",
		exp: "APPLE MGNA3TU/A MacBook Air 13.3&quot; Apple M1/512GB SSD/ Laptop Silver",
		details: "HP Dizüstü",
		color: ["gray", "black", "silver"],
		detailedlist: ["Intel® Core™ i3-1115G8", "Tümleşik: Intel® Grafik Kartı", "13.3&quot;", "256 GB", "Full-HD", "15.6&quot;", "1920 x 1080"],
		price: 8837.7,
		discount: 30,
		attributes: ["Intel® Core™ i3-1115G8", "Tümleşik: Intel® Grafik Kartı", "13.3&quot;", "256 GB", "Full-HD", "15.6&quot;", "1920 x 1080"],
		images: ["4P3S3ES-2.webp", "4P3S3ES-1.webp", "4P3S3ES-3.webp"],
		featured: true,
		slider: true,
    featuredbg: "dodgerblue"
	},
])